apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-service
data:
  APP_NAME: "analytics-service"
  LOG_LEVEL: "INFO"
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
