apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: flag-service
data:
  APP_NAME: "flag-service"
  LOG_LEVEL: "INFO"
  PORT: "8002"
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service.auth-service.svc.cluster.local:8000"
  FLAG_SERVICE_URL: "http://flag-service.flag-service.svc.cluster.local:8002"
