apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-service
  labels:
    app: flag-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
        version: "1.0"
    spec:
      containers:
      - name: flag-service
        image: 589138972429.dkr.ecr.us-east-1.amazonaws.com/a/flag-service:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8002
          protocol: TCP
        
        # Variáveis de ambiente
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flag-service-secrets
              key: DATABASE_URL
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: flag-service-config
              key: AUTH_SERVICE_URL
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: flag-service-config
              key: APP_NAME
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: flag-service-config
              key: LOG_LEVEL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: flag-service-config
              key: PORT
        
        # Resource requests e limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        
        # # Readiness Probe
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8002
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        
        # # Liveness Probe
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8002
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        
        # # Startup Probe
        # startupProbe:
        #   httpGet:
        #     path: /health
        #     port: 8002
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 30
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flag-service
              topologyKey: kubernetes.io/hostname
