{{- range $name, $svc := .Values.services -}}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "togglemaster.fullname" $ }}-{{ $name }}
  labels:
    app.kubernetes.io/name: {{ include "togglemaster.name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ default 1 $svc.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: {{ $name }}
    spec:
{{ if or $.Values.serviceAccount.create $.Values.serviceAccount.name }}
      serviceAccountName: {{ include "togglemaster.serviceAccountName" $ }}
{{ end }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml $.Values.tolerations | nindent 6 }}
      affinity: {{ toYaml $.Values.affinity | nindent 6 }}
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" $svc.image.pullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}
              name: http
          env:
            - name: PORT
              value: "{{ $svc.port }}"
{{ range $key, $value := $svc.env }}
{{ if ne $value "" }}
            - name: {{ $key }}
              value: {{ quote $value }}
{{ end }}
{{ end }}
          resources:
{{ toYaml $svc.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
---
{{- end }}
{{- end }}
