{{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "togglemaster.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "togglemaster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
---
{{- end }}
