serviceAccount:
  create: false
  name: ""
  annotations: {}

imagePullSecrets: []

nodeSelector: {}
tolerations: []
affinity: {}

services:
  auth-service:
    enabled: true
    image:
      repository: 589138972429.dkr.ecr.us-east-1.amazonaws.com/a/auth-service
      tag: latest
      pullPolicy: IfNotPresent
    port: 8000
    service:
      type: ClusterIP
      port: 8000
    replicas: 2
    env:
      DATABASE_URL: ""
      MASTER_KEY: ""
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

  flag-service:
    enabled: true
    image:
      repository: 589138972429.dkr.ecr.us-east-1.amazonaws.com/a/flag-service
      tag: latest
      pullPolicy: IfNotPresent
    port: 8002
    service:
      type: ClusterIP
      port: 8002
    replicas: 2
    env:
      DATABASE_URL: ""
      AUTH_SERVICE_URL: ""
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi

  targeting-service:
    enabled: true
    image:
      repository: 589138972429.dkr.ecr.us-east-1.amazonaws.com/a/targeting-service
      tag: latest
      pullPolicy: IfNotPresent
    port: 8003
    service:
      type: ClusterIP
      port: 8003
    replicas: 2
    env:
      DATABASE_URL: ""
      AUTH_SERVICE_URL: ""
      REDIS_URL: ""
      FLAG_SERVICE_URL: ""
      TARGETING_SERVICE_URL: ""
      AWS_SQS_URL: ""
      AWS_REGION: ""
    resources:
      requests:
        cpu: 150m
        memory: 192Mi
      limits:
        cpu: 300m
        memory: 384Mi

  evaluation-service:
    enabled: true
    image:
      repository: 589138972429.dkr.ecr.us-east-1.amazonaws.com/a/evaluation-service
      tag: latest
      pullPolicy: IfNotPresent
    port: 8004
    service:
      type: ClusterIP
      port: 8004
    replicas: 2
    env:
      REDIS_URL: ""
      FLAG_SERVICE_URL: ""
      TARGETING_SERVICE_URL: ""
      AWS_SQS_URL: ""
      AWS_REGION: ""
    resources:
      requests:
        cpu: 150m
        memory: 192Mi
      limits:
        cpu: 300m
        memory: 384Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70

  analytics-service:
    enabled: true
    image:
      repository: 589138972429.dkr.ecr.us-east-1.amazonaws.com/a/analytics-service
      tag: latest
      pullPolicy: IfNotPresent
    port: 8005
    service:
      type: ClusterIP
      port: 8005
    replicas: 1
    env:
      AWS_REGION: ""
      AWS_SQS_URL: ""
      AWS_DYNAMODB_TABLE: ""
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
